imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration

#assetic:
    # java: "/usr/bin/java"
#    filters:
#        yui_css:
#            jar: "%kernel.root_dir%/Resources/java/yuicompressor.jar"
#        yui_js:
#            jar: "%kernel.root_dir%/Resources/java/yuicompressor.jar"
#
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:
        - EtheriqLesson5Bundle
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
    assets:
        assets_css:
            inputs:
                - %kernel.root_dir%/../vendor/twbs/bootstrap/docs/assets/css/bootstrap.css
            #   - %kernel.root_dir%/../src/Etheriq/Lesson5Bundle/Resources/public/css/bootstrap.css
            #   - %kernel.root_dir%/../src/Etheriq/Lesson5Bundle/Resources/public/css/bootstrap-responsive.css
            filters:
                - cssrewrite
            output: css/bootstrap-style.css
        jquery:
            inputs:
                - %kernel.root_dir%/../vendor/components/jquery/jquery.js
            #   - %kernel.root_dir%/../src/Etheriq/Lesson5Bundle/Resources/public/js/jquery-1.10.2.min.js
            output: js/jquery.js
        javaScript-bootstrap:
            inputs:
               - %kernel.root_dir%/../vendor/twbs/bootstrap/docs/assets/js/bootstrap.js
            #   - %kernel.root_dir%/../src/Etheriq/Lesson5Bundle/Resources/public/js/bootstrap.js
            output: js/bootstrap.js
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }
