parameters:
#    etheriq_lesson5.example.class: Etheriq\Lesson5Bundle\Example

services:
#    etheriq_lesson5.example:
#        class: %etheriq_lesson5.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
